// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLnrhJM2n2D9BLmtdKg0OeMpG89peTjUg',
    appId: '1:464056919731:web:333a8a101aeeb1cbcdb2c6',
    messagingSenderId: '464056919731',
    projectId: 'chatx-v2-a88a5',
    authDomain: 'chatx-v2-a88a5.firebaseapp.com',
    storageBucket: 'chatx-v2-a88a5.firebasestorage.app',
    measurementId: 'G-DC6CT96R10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYamgBB9WfUeiIuWa_F7WSUzWD_0wEZ2A',
    appId: '1:464056919731:android:dff54a600ee9d936cdb2c6',
    messagingSenderId: '464056919731',
    projectId: 'chatx-v2-a88a5',
    storageBucket: 'chatx-v2-a88a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjN5_1f39N0Ix4aU-350i9vV3z6RzXOOw',
    appId: '1:464056919731:ios:62cee83627167ccbcdb2c6',
    messagingSenderId: '464056919731',
    projectId: 'chatx-v2-a88a5',
    storageBucket: 'chatx-v2-a88a5.firebasestorage.app',
    iosBundleId: 'com.example.chatxInterviewTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjN5_1f39N0Ix4aU-350i9vV3z6RzXOOw',
    appId: '1:464056919731:ios:62cee83627167ccbcdb2c6',
    messagingSenderId: '464056919731',
    projectId: 'chatx-v2-a88a5',
    storageBucket: 'chatx-v2-a88a5.firebasestorage.app',
    iosBundleId: 'com.example.chatxInterviewTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLnrhJM2n2D9BLmtdKg0OeMpG89peTjUg',
    appId: '1:464056919731:web:9f6974db380f2dd1cdb2c6',
    messagingSenderId: '464056919731',
    projectId: 'chatx-v2-a88a5',
    authDomain: 'chatx-v2-a88a5.firebaseapp.com',
    storageBucket: 'chatx-v2-a88a5.firebasestorage.app',
    measurementId: 'G-MVN7F0Y38E',
  );

}
